services:
  booking-api:
    build: .
    image: recipe-api
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PATH: ${DB_PATH}
      API_USERNAME: ${API_USERNAME}
      API_PASSWORD: ${API_PASSWORD}
      GUMLOOP_API_URL: ${GUMLOOP_API_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: recipes_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: